name: node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages on client folder then build pages
        env:
          CI: false
        run: |
          cd client
          touch .env
          echo REACT_APP_API_LOGIN=${{secrets.REACT_APP_API_LOGIN}} >> .env
          echo REACT_APP_API_REGISTER=${{secrets.REACT_APP_API_REGISTER}} >> .env
          echo REACT_APP_API_USER=${{secrets.REACT_APP_API_USER}} >> .env
          echo REACT_APP_API_REFRESH=${{secrets.REACT_APP_API_REFRESH}} >> .env
          echo REACT_APP_API_WRFGEN=${{secrets.REACT_APP_API_WRFGEN}} >> .env
          npm install 
          npm run build
      - name: Deploy the production to server
        run: |
          cd /var/www/lokana-app/_work/lokana-app/lokana-app
          touch .env
          echo DB_URI_DEV=${{secrets.DB_URI_DEV}} >> .env
          echo DB_URI_PROD=${{secrets.DB_URI_PROD}} >> .env
          echo CORS_ORIGIN=${{secrets.CORS_ORIGIN}} >> .env
          echo ACCESS_TOKEN_SECRET=${{secrets.ACCESS_TOKEN_SECRET}} >> .env
          echo REFRESH_TOKEN_SECRET=${{secrets.REFRESH_TOKEN_SECRET}} >> .env
          npm install
          pm2 stop lokana-app
          pm2 start lokana-app
          pm2 save
          sudo service nginx restart
          echo "Deployment success"
